"""Add_file_fields_to_document

Revision ID: e372e2cb352f
Revises: f37d822640a7
Create Date: 2025-03-27 15:14:37.540051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e372e2cb352f'
down_revision: Union[str, None] = 'f37d822640a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('related_document_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'documents', 'documents', ['related_document_id'], ['id'])
    op.drop_column('documents', 'replacement_doc_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('replacement_doc_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'related_document_id')
    # ### end Alembic commands ###
