"""Add many-to-many tables

Revision ID: e770bcfa6fa4
Revises: 888286bdccdc
Create Date: 2025-03-27 21:49:04.462098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e770bcfa6fa4'
down_revision: Union[str, None] = '888286bdccdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_document_approvers',
    sa.Column('user_document_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_document_id'], ['ud.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_document_id', 'user_id')
    )
    op.create_table('user_document_reviewers',
    sa.Column('user_document_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_document_id'], ['ud.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_document_id', 'user_id')
    )
    op.drop_constraint('ud_approved_by_fkey', 'ud', type_='foreignkey')
    op.drop_constraint('ud_reviewer_id_fkey', 'ud', type_='foreignkey')
    op.drop_column('ud', 'reviewer_id')
    op.drop_column('ud', 'approved_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ud', sa.Column('approved_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ud', sa.Column('reviewer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('ud_reviewer_id_fkey', 'ud', 'users', ['reviewer_id'], ['id'])
    op.create_foreign_key('ud_approved_by_fkey', 'ud', 'users', ['approved_by'], ['id'])
    op.drop_table('user_document_reviewers')
    op.drop_table('user_document_approvers')
    # ### end Alembic commands ###
